// <auto-generated />
using System;
using Concertable.Payment.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.Payment.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260826094428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.CommissionBindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CommissionConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayerReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ReviewedGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeSetupIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CommissionConfigurationId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("StripeSetupIntentId")
                        .IsUnique()
                        .HasFilter("[StripeSetupIntentId] IS NOT NULL");

                    b.HasIndex("ExternalReference", "PayerReference")
                        .IsUnique();

                    b.ToTable("CommissionBindings", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.CommissionConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Rate")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("RatePercentage");

                    b.HasKey("Id");

                    b.ToTable("CommissionConfigurations", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_CommissionConfigurations_RatePercentage", "[RatePercentage] > 0 AND [RatePercentage] <= 100");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.EscrowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ChargeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CommissionBindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CommissionGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionNetMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionVatMinor")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CommissionVatRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("CommissionVatRatePercentage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("FromOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PayeeGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("PayerTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("RefundedGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransferId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ChargeId")
                        .IsUnique();

                    b.HasIndex("CommissionBindingId")
                        .IsUnique()
                        .HasFilter("[CommissionBindingId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("Escrows", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.FinancialOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("LastAttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("Status");

                    b.ToTable("FinancialOperations", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type", "OwnerId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("IX_LedgerAccounts_Type_OwnerId_Currency");

                    b.ToTable("LedgerAccounts", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("LedgerAccountId")
                        .HasColumnType("int");

                    b.Property<int>("LedgerTransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LedgerAccountId");

                    b.HasIndex("LedgerTransactionId");

                    b.ToTable("LedgerEntries", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PostingType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PaymentIntentId");

                    b.HasIndex("PostingType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_LedgerTransactions_PostingType_ExternalId");

                    b.ToTable("LedgerTransactions", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentRefundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CommissionRefundedMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionVatReversedMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("EscrowId")
                        .HasColumnType("int");

                    b.Property<long>("GrossRefundedMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PayerTotalRefundedMinor")
                        .HasColumnType("bigint");

                    b.Property<int?>("SettlementTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EscrowId");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasFilter("[OperationId] IS NOT NULL");

                    b.HasIndex("SettlementTransactionId");

                    b.HasIndex("StripeRefundId")
                        .IsUnique()
                        .HasFilter("[StripeRefundId] IS NOT NULL");

                    b.ToTable("PaymentRefunds", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentRefunds_Owner", "([EscrowId] IS NULL AND [SettlementTransactionId] IS NOT NULL) OR ([EscrowId] IS NOT NULL AND [SettlementTransactionId] IS NULL)");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionAttemptEntity", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CaptureBefore")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("LastAttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastObservedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastProviderEventCreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastProviderEventId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastProviderStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("NextReconcileAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PredecessorAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderDiagnosticCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderDiagnosticMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProviderObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderObjectKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AttemptId");

                    b.HasIndex("NextReconcileAt");

                    b.HasIndex("State");

                    b.HasIndex("OperationId", "PredecessorAttemptId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentSessionAttempts_OperationId_PredecessorAttemptId")
                        .HasFilter("[PredecessorAttemptId] IS NOT NULL");

                    b.HasIndex("OperationId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentSessionAttempts_OperationId_Revision");

                    b.HasIndex("ProviderObjectKind", "ProviderObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentSessionAttempts_ProviderObjectKind_ProviderObjectId")
                        .HasFilter("[ProviderObjectId] IS NOT NULL");

                    b.ToTable("PaymentSessionAttempts", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentSessionAttempts_ProviderBinding", "[ProviderObjectId] IS NOT NULL OR [State] = 'Creating'");

                            t.HasCheckConstraint("CK_PaymentSessionAttempts_Revision", "[Revision] >= 1");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionOperationEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConsumerCorrelation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("FingerprintVersion")
                        .HasColumnType("int");

                    b.Property<string>("FundsRouting")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayeeOwnerKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayerOwnerKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderConnectedAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SessionKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("OperationId");

                    b.HasIndex("PayeeOwnerKey");

                    b.HasIndex("PayerOwnerKey");

                    b.HasIndex("OperationType", "ConsumerCorrelation");

                    b.ToTable("PaymentSessionOperations", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentSessionOperations_CurrentRevision", "[CurrentRevision] >= 1");

                            t.HasCheckConstraint("CK_PaymentSessionOperations_FingerprintVersion", "[FingerprintVersion] >= 1");

                            t.HasCheckConstraint("CK_PaymentSessionOperations_RequestFingerprint", "LEN([RequestFingerprint]) = 64");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PayoutAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.HasIndex("StripeAccountId");

                    b.HasIndex("StripeCustomerId");

                    b.ToTable("PayoutAccounts", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.StripeEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EventProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("StripeEvents", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PayeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayeeId");

                    b.HasIndex("PayerId");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.ToTable("Transactions", "payment");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TransactionEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.Entities.TransactionEntity");

                    b.Property<int>("BookingId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ContextId");

                    b.Property<Guid?>("CommissionBindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CommissionGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionNetMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionVatMinor")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CommissionVatRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("CommissionVatRatePercentage");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("PayeeGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("PayerTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("RefundedGrossMinor")
                        .HasColumnType("bigint");

                    b.HasIndex("CommissionBindingId")
                        .IsUnique()
                        .HasFilter("[CommissionBindingId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("SettlementTransactionEntity");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.TicketTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.Entities.TransactionEntity");

                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ContextId");

                    b.HasDiscriminator().HasValue("TicketTransactionEntity");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.VerifyTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.Entities.TransactionEntity");

                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ContextId");

                    b.HasDiscriminator().HasValue("VerifyTransactionEntity");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.CommissionBindingEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.CommissionConfigurationEntity", "CommissionConfiguration")
                        .WithMany()
                        .HasForeignKey("CommissionConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommissionConfiguration");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.EscrowEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.CommissionBindingEntity", "CommissionBinding")
                        .WithMany()
                        .HasForeignKey("CommissionBindingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissionBinding");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerEntryEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.LedgerAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concertable.Payment.Domain.Entities.LedgerTransactionEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentRefundEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.EscrowEntity", "Escrow")
                        .WithMany("Refunds")
                        .HasForeignKey("EscrowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", "SettlementTransaction")
                        .WithMany("Refunds")
                        .HasForeignKey("SettlementTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Escrow");

                    b.Navigation("SettlementTransaction");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionAttemptEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.PaymentSessionOperationEntity", null)
                        .WithMany("Attempts")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.CommissionBindingEntity", "CommissionBinding")
                        .WithMany()
                        .HasForeignKey("CommissionBindingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissionBinding");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.EscrowEntity", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerTransactionEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionOperationEntity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", b =>
                {
                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
