// <auto-generated />
using System;
using Concertable.Payment.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concertable.Payment.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAtUtc");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.CommissionBindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CommissionConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayerReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ReviewedGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripeSetupIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CommissionConfigurationId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("\"StripePaymentIntentId\" IS NOT NULL");

                    b.HasIndex("StripeSetupIntentId")
                        .IsUnique()
                        .HasFilter("\"StripeSetupIntentId\" IS NOT NULL");

                    b.HasIndex("ExternalReference", "PayerReference")
                        .IsUnique();

                    b.ToTable("CommissionBindings", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.CommissionConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("RatePercentage");

                    b.HasKey("Id");

                    b.ToTable("CommissionConfigurations", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_CommissionConfigurations_RatePercentage", "\"RatePercentage\" > 0 AND \"RatePercentage\" <= 100");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.EscrowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CommissionBindingId")
                        .HasColumnType("uuid");

                    b.Property<long>("CommissionGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionNetMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionVatMinor")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CommissionVatRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("CommissionVatRatePercentage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("FromOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PayeeGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("PayerTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("RefundedGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("ReleaseOperationFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int?>("ReleaseOperationFingerprintVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReleaseOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId")
                        .IsUnique();

                    b.HasIndex("CommissionBindingId")
                        .IsUnique()
                        .HasFilter("\"CommissionBindingId\" IS NOT NULL");

                    b.HasIndex("ReleaseOperationId")
                        .IsUnique()
                        .HasFilter("\"ReleaseOperationId\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("OperationType", "ClientReference")
                        .IsUnique();

                    b.ToTable("Escrows", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.FinancialOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("OperationType", "ClientReference");

                    b.ToTable("FinancialOperations", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type", "OwnerId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("IX_LedgerAccounts_Type_OwnerId_Currency");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Type", "OwnerId", "Currency"), false);

                    b.ToTable("LedgerAccounts", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("LedgerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("LedgerTransactionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LedgerAccountId");

                    b.HasIndex("LedgerTransactionId");

                    b.ToTable("LedgerEntries", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("text");

                    b.Property<int>("PostingType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentIntentId");

                    b.HasIndex("OperationType", "ClientReference");

                    b.HasIndex("PostingType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_LedgerTransactions_PostingType_ExternalId");

                    b.ToTable("LedgerTransactions", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentRefundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("CommissionRefundedMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionVatReversedMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscrowId")
                        .HasColumnType("integer");

                    b.Property<long>("GrossRefundedMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<long>("PayerTotalRefundedMinor")
                        .HasColumnType("bigint");

                    b.Property<int?>("SettlementTransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EscrowId");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasFilter("\"OperationId\" IS NOT NULL");

                    b.HasIndex("SettlementTransactionId");

                    b.HasIndex("StripeRefundId")
                        .IsUnique();

                    b.ToTable("PaymentRefunds", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentRefunds_Owner", "(\"EscrowId\" IS NULL AND \"SettlementTransactionId\" IS NOT NULL) OR (\"EscrowId\" IS NOT NULL AND \"SettlementTransactionId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionAttemptEntity", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CaptureBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastProviderEventCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastProviderEventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastProviderStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("NextReconcileAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PredecessorAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderDiagnosticCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderDiagnosticMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProviderObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderObjectKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AttemptId");

                    b.HasIndex("NextReconcileAt");

                    b.HasIndex("State");

                    b.HasIndex("OperationId", "PredecessorAttemptId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentSessionAttempts_OperationId_PredecessorAttemptId")
                        .HasFilter("\"PredecessorAttemptId\" IS NOT NULL");

                    b.HasIndex("OperationId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentSessionAttempts_OperationId_Revision");

                    b.HasIndex("ProviderObjectKind", "ProviderObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentSessionAttempts_ProviderObjectKind_ProviderObjectId")
                        .HasFilter("\"ProviderObjectId\" IS NOT NULL");

                    b.ToTable("PaymentSessionAttempts", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentSessionAttempts_ProviderBinding", "\"ProviderObjectId\" IS NOT NULL OR \"State\" = 'Creating'");

                            t.HasCheckConstraint("CK_PaymentSessionAttempts_Revision", "\"Revision\" >= 1");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionOperationEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<long?>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("FingerprintVersion")
                        .HasColumnType("integer");

                    b.Property<string>("FundsRouting")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("MandateAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MandateTermsVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayeeOwnerKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayerOwnerKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderConnectedAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SessionKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("OperationId");

                    b.HasIndex("PayeeOwnerKey");

                    b.HasIndex("PayerOwnerKey");

                    b.HasIndex("OperationType", "ClientReference")
                        .IsUnique();

                    b.ToTable("PaymentSessionOperations", "payment", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentSessionOperations_CurrentRevision", "\"CurrentRevision\" >= 1");

                            t.HasCheckConstraint("CK_PaymentSessionOperations_FingerprintVersion", "\"FingerprintVersion\" >= 1");

                            t.HasCheckConstraint("CK_PaymentSessionOperations_MandateEvidence", "(\"MandateTermsVersion\" IS NULL AND \"MandateAcceptedAt\" IS NULL) OR (\"MandateTermsVersion\" IS NOT NULL AND \"MandateAcceptedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PaymentSessionOperations_RequestFingerprint", "char_length(\"RequestFingerprint\") = 64");
                        });
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PayoutAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.HasIndex("StripeAccountId");

                    b.HasIndex("StripeCustomerId");

                    b.ToTable("PayoutAccounts", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.StripeEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("StripeEvents", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PayeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PayeeId");

                    b.HasIndex("PayerId");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.HasIndex("OperationType", "ClientReference");

                    b.ToTable("Transactions", "payment");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TransactionEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.Entities.TransactionEntity");

                    b.HasDiscriminator().HasValue("PaymentTransactionEntity");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.Entities.TransactionEntity");

                    b.Property<Guid?>("CommissionBindingId")
                        .HasColumnType("uuid");

                    b.Property<long>("CommissionGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionNetMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionVatMinor")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CommissionVatRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("CommissionVatRatePercentage");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("OperationFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int?>("OperationFingerprintVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<long>("PayeeGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("PayerTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("RefundedGrossMinor")
                        .HasColumnType("bigint");

                    b.Property<bool>("RequiresAction")
                        .HasColumnType("boolean");

                    b.HasIndex("CommissionBindingId")
                        .IsUnique()
                        .HasFilter("\"CommissionBindingId\" IS NOT NULL");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasFilter("\"OperationId\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("SettlementTransactionEntity");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.VerifyTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.Entities.TransactionEntity");

                    b.HasDiscriminator().HasValue("VerifyTransactionEntity");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.CommissionBindingEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.CommissionConfigurationEntity", "CommissionConfiguration")
                        .WithMany()
                        .HasForeignKey("CommissionConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommissionConfiguration");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.EscrowEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.CommissionBindingEntity", "CommissionBinding")
                        .WithMany()
                        .HasForeignKey("CommissionBindingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissionBinding");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerEntryEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.LedgerAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concertable.Payment.Domain.Entities.LedgerTransactionEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentRefundEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.EscrowEntity", "Escrow")
                        .WithMany("Refunds")
                        .HasForeignKey("EscrowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", "SettlementTransaction")
                        .WithMany("Refunds")
                        .HasForeignKey("SettlementTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Escrow");

                    b.Navigation("SettlementTransaction");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionAttemptEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.PaymentSessionOperationEntity", null)
                        .WithMany("Attempts")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.Entities.CommissionBindingEntity", "CommissionBinding")
                        .WithMany()
                        .HasForeignKey("CommissionBindingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissionBinding");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.EscrowEntity", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.LedgerTransactionEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.PaymentSessionOperationEntity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.Entities.SettlementTransactionEntity", b =>
                {
                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
